run:
  build-tags:
    - test

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - goconst
        - lll
        - dupl

linters-settings:
  funlen:
    statements: 50

  gocyclo:
    min-complexity: 25

  gocognit:
    min-complexity: 40

  lll:
    line-length: 140
    tab-width: 2

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - maligned
    - misspell
    - nakedret
    - prealloc
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
  # - unused   disabled due to high memory consumption. See https://github.com/golangci/golangci-lint/issues/994
    - varcheck
    - whitespace

  # don't enable:
  # - gochecknoglobals
  # - gochecknoinits
